create table if not exists public.batchcutout_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  email text not null,
  plan text not null default 'free',
  plan_status text not null default 'active',
  batch_limit integer not null default 2,
  monthly_image_limit integer not null default 0,
  monthly_images_used integer not null default 0,
  stripe_customer_id text,
  stripe_subscription_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists batchcutout_users_plan_idx
  on public.batchcutout_users(plan, plan_status);

create index if not exists batchcutout_users_email_idx
  on public.batchcutout_users(email);

create index if not exists batchcutout_users_user_id_idx
  on public.batchcutout_users(user_id);
